language: objective-c
xcode_project: Pantomime.xcodeproj
xcode_scheme: Pantomime (iOS)
osx_image: xcode10.1
xcode_sdk: iphonesimulator12.1
before_install:
- gem install xcpretty
script:
- set -o pipefail  # required to let xcpretty use the same exit code like xcodebuild
- xcodebuild -project Pantomime.xcodeproj -scheme "Pantomime (iOS)" -destination name="iPhone 6" -destination name="iPhone 6" test | xcpretty -c
